name: C/C++ CI

on:
  workflow_dispatch:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
          name: "windows 2019",
          os: windows-2019,
          generators: "Visual Studio 16 2019"
          }
        - {
          name: "ubuntu-20.04",
          os: ubuntu-20.04,
          cc: "gcc",
          cxx: "g++",
          generators: "Unix Makefiles"
          }
        - {
          name: "macos-11",
          os: macos-11,
          cc: "clang",
          cxx: "clang++",
          generators: "Unix Makefiles"
          }

    steps:
    - uses: actions/checkout@v2

    - name: Install boost (windows)
      if: startsWith(matrix.config.name, 'windows')
      run: choco install boost-msvc-14.1

    - name: Install boost (ubuntu)
      if: startsWith(matrix.config.name, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-filesystem-dev
  
    - name: Install boost (macos)
      if: startsWith(matrix.config.name, 'macos')
      run: brew install boost

    - name: configure
      run: cmake -S src -B CIBuild -DCMAKE_BUILD_TYPE=Release -G "${{ matrix.config.generators }}"

    - name: make
      run: cmake --build CIBuild -j2 --config Release

    - name: make test
      run: |
        cd CIBuild
        ctest -V -C Release

    - name: make install
      run:  |
        cd CIBuild
        cmake --install CIInstall
