name: C/C++ CI

on:
  workflow_dispatch:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
          name: "windows 2019",
          os: windows-2019,
          generators: "Visual Studio 16 2019",
          toolset: "msvc",
          platform_version: "2019"
          }
        - {
          name: "ubuntu-20.04",
          os: ubuntu-20.04,
          cc: "gcc",
          cxx: "g++",
          generators: "Unix Makefiles",
          toolset: "gcc",
          platform_version: "20.04"
          }
        - {
          name: "macos-11",
          os: macos-11,
          cc: "clang",
          cxx: "clang++",
          generators: "Unix Makefiles",
          toolset: "clang",
          platform_version: "11"
          }

    steps:
    - uses: actions/checkout@v2

    - name: Install boost
      uses: MarkusJx/install-boost@v2.1.0
      id: install-boost
      with:
        boost_version: 1.78.0
        platform_version: ${{ matrix.config.platform_version }}
        toolset: ${{ matrix.config.toolset }}

    - name: configure
      run: cmake -S src -B CIBuild -DCMAKE_INSTALL_PREFIX=CIInstall -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -G "${{ matrix.config.generators }}"
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

    - name: make
      run: cmake --build CIBuild -j2 --config Release

    - name: make test
      run: |
        cd CIBuild
        ctest -V -C Release

    - name: make install
      run: cmake --build CIBuild --target install --config Release
